### ISSUE TITLE
Including bootstrap.min.js causes multiple video backgrounds to break

### ISSUE THREAD

**Issue by mardanlin** [linnett/backgroundVideo#29]
If you have more than one video background on a page, including bootstrap.js will cause all videos after first to break. Have tested this and reduced issue single handed to the boostrap js file.

**Comment by bxlxux** [comment]
I'm running into the same issue. Is there a way to make the multiple videos work with bootstrap.js?

**Comment by linnett** [comment]
In fairness I've never used it with Bootstrap but I don't know why it would cause a problem. Can you provide a codepen or something so I can see the issue?

**Comment by bxlxux** [comment]
Thanks for the quick reply! Here's one that I started, but I don't have pro on codepen so can't upload files. I tried referencing a video through http: but I think this isn't working as reported in issue #30.

http://codepen.io/bxlxux/pen/JNovLb

**Comment by linnett** [comment]
I think the referencing to videos will work if the last part of the URL is
the file type.

I just checked your codepen. It looks like the JS was not loaded in the
codepen before BackgroundVideo was getting returned. So therefore, putting
it in the script tags didn't work. I moved the JS under the plugin code and
you can see now that it works.

Your problem with Bootstrap might be because you haven't references jQuery
(check the console logs and you'll see what I'm talking about). As far as I
can see, the plugin is working as I'd expect.


*Sam Linnett*
Director, Sam Linnett Ltd
07446 150 449 | sam@linnett.co.uk | http://www.samlinnett.com
<http://uk.linkedin.com/in/samlinnett>  <http://twitter.com/sam_linnett>
<http://github.com/linnett>

**Comment by bxlxux** [comment]
Okay thank you. I got a bit lazy with generating that code pen and did leave off the jquery. I fixed it. As you suggested I'll have to read up on Babel with grunt. The src file was just easier to read. Many thanks, I'll go back and integrate to see what may be happening in my code.
