### ISSUE TITLE
parallax video

### ISSUE THREAD

**Issue by marwanus** [linnett/backgroundVideo#4]
Hi linnett,

Looks like the background video is not working on smartphones, I have only a black background.
even though I didn't see the issue when decreasing my destop navigator size.

Thanks for your help !

**Comment by linnett** [comment]
Hi,

Unfortunately, it will not work on mobile devices (as noted in the
documentation). This is because smartphones and tablets have major
limitations to HTML5 video and parallax on scroll.

On touch devices, HTML5 video does not work on autoplay, which means the
user would have to press a play button. Therefore using a background video
would be pointless. Also, the parallax would not work because JavaScript
rendering us paused on scroll for many devices and on others, the
JavaScript engine simply cannot handle the speed it needs to work.

I suggest an image fallback, perhaps using Modernizr to detect video.
Remember, on mobile devices you also don't want to overload the user with
high traffic. Videos should be optional not compulsory.
